version: '3.8'

services:
  h2-database:
    image: oscarfonts/h2:latest
    container_name: h2-container
    ports:
      - "8080:8080"
    volumes:
      - ./data:/h2-data
    environment:
      - H2_OPTIONS=-ifNotExists
    networks:
      - h2-network

networks:
  h2-network:
    driver: bridge
